export const AUTH_START = "AUTH_START";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const LOG_OUT = "LOG_OUT";

export const FETCH_ACCOUNT_START = "FETCH_ACCOUNT_START";
export const FETCH_ACCOUNT_FAILED = "FETCH_ACCOUNT_FAILED";
export const FETCH_ACCOUNT_SUCCESS = "FETCH_ACCOUNT_SUCCESS";

export const UPDATE_ACCOUNT_START = "UPDATE_ACCOUNT_START";
export const UPDATE_ACCOUNT_FAILED = "UPDATE_ACCOUNT_FAILED";
export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS";

export const UPLOAD_PROFILE_PHOTO_START = "UPLOAD_PROFILE_PHOTO_START";
export const UPLOAD_PROFILE_PHOTO_FAILED = "UPLOAD_PROFILE_PHOTO_FAILED";
export const UPLOAD_PROFILE_PHOTO_SUCCESS = "UPLOAD_PROFILE_PHOTO_SUCCESS";

export const FETCH_VENDORS_START = "FETCH_VENDORS_START";
export const FETCH_VENDORS_FAILED = "FETCH_VENDORS_FAILED";
export const FETCH_VENDORS_SUCCESS = "FETCH_VENDORS_SUCCESS";

export const REGISTER_USER_WILL_START = "REGISTER_USER_WILL_START";
export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
